---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jobmatch
  namespace: jobmatch-local-dev
spec:
  chart:
    spec:
      chart: ./platform/helm
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: jobmatch
  interval: 1m0s
