apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: local-k8s-store
spec:
  provider:
    kubernetes:
      remoteNamespace: jobmatch-dev
      server:
        url: "https://kubernetes.default.svc"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: external-secrets
      auth:
        serviceAccount:
          name: external-secrets-external-secrets
          namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gemini-auth-secret
  namespace: agentgateway-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: local-k8s-store
    kind: ClusterSecretStore
  target:
    name: gemini-auth-secret
    creationPolicy: Owner
  data:
    - secretKey: Authorization
      remoteRef:
        key: llm-secrets
        property: gemini-api-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: claude-auth-secret
  namespace: agentgateway-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: local-k8s-store
    kind: ClusterSecretStore
  target:
    name: claude-auth-secret
    creationPolicy: Owner
  data:
    - secretKey: Authorization
      remoteRef:
        key: llm-secrets
        property: claude-api-key
---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: gemini-backend
  namespace: agentgateway-system
spec:
  ai:
    provider:
      gemini:
        model: gemini-2.5-flash-lite
      host: mock-llm.jobmatch-dev.svc.cluster.local
      port: 8089
      path: /post
  policies:
    auth:
      secretRef:
        name: gemini-auth-secret
---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: claude-backend
  namespace: agentgateway-system
spec:
  ai:
    provider:
      anthropic:
        model: claude-haiku-4-5
      host: mock-llm.jobmatch-dev.svc.cluster.local
      port: 8089
      path: /post
  policies:
    auth:
      secretRef:
        name: claude-auth-secret
