apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: llm-secrets
  namespace: jobmatch-dev
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore

  target:
    name: llm-secrets
    creationPolicy: Owner

  data:
    - secretKey: gemini-api-key
      remoteRef:
        key: gemini-api-key                