apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-bootstrap
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./platform/flux/clusters/dev/infra
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: scout-apps-bootstrap
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./platform/flux/clusters/dev/apps/jobmatch
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
  dependsOn:
    - name: infra-bootstrap  
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: observability-bootstrap
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./platform/flux/clusters/dev/observability
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
