apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: jobmatch
  namespace: jobmatch-local-dev
spec:
  interval: 1m0s
  ref:
    branch: dev
  url: https://github.com/mkdir28/hackathon-devops
