apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flux-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mkdir28/hackathon-devops.git'
    targetRevision: develop
    path: platform/base/flux-manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: flux-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true