apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Pavel containers from GHCR
images:
  - name: jobmatch-api-placeholder
    newName: ghcr.io/mkdir28/jobmatch-api
    newTag: latest
  - name: jobmatch-web-placeholder
    newName: ghcr.io/mkdir28/jobmatch-web
    newTag: latest