apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: "happy-deploys-job-searcher"
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-sa-key
            key: key.json
            namespace: external-secrets
