apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jobmatch.fullname" . }}-skills
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jobmatch.labels" . | nindent 4 }}
data:
  {{- range $path, $_ :=  .Files.Glob "skills/**/SKILL.md" }}
  {{- $key := printf "%s.md" (dir $path | base) }}
  {{ $key }}: |
{{ $.Files.Get $path | indent 4 }}
  {{- end }}
