apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jobmatch.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
  selector:
    {{- include "jobmatch.selectorLabels" . | nindent 4 }}
    app: {{ include "jobmatch.fullname" . }}-api
